-- Ajout du statut 'archivee' à l'enum campagne_statut
ALTER TYPE campagne_statut ADD VALUE IF NOT EXISTS 'archivee';
--> Statement-breakpoint
CREATE TABLE IF NOT EXISTS "archives_campagnes" (
  "id" serial PRIMARY KEY NOT NULL,
  "cooperative_id" integer NOT NULL REFERENCES "cooperatives"("id"),
  "campagne_id" integer NOT NULL REFERENCES "campagnes"("id"),
  "tonnage_total_kg" numeric(14, 2) DEFAULT '0',
  "tonnage_membres_kg" numeric(14, 2) DEFAULT '0',
  "tonnage_pisteurs_kg" numeric(14, 2) DEFAULT '0',
  "tonnage_externes_kg" numeric(14, 2) DEFAULT '0',
  "nb_livraisons" integer DEFAULT 0,
  "nb_membres_actifs" integer DEFAULT 0,
  "nb_fournisseurs_total" integer DEFAULT 0,
  "prix_achat_moyen_kg_fcfa" numeric(12, 2) DEFAULT '0',
  "prix_vente_moyen_kg_fcfa" numeric(12, 2) DEFAULT '0',
  "ca_ventes_fcfa" numeric(16, 2) DEFAULT '0',
  "cout_achats_fcfa" numeric(16, 2) DEFAULT '0',
  "charges_exploitation_fcfa" numeric(16, 2) DEFAULT '0',
  "charges_personnel_fcfa" numeric(16, 2) DEFAULT '0',
  "marge_brute_fcfa" numeric(16, 2) DEFAULT '0',
  "marge_nette_fcfa" numeric(16, 2) DEFAULT '0',
  "marge_kg_fcfa" numeric(12, 2) DEFAULT '0',
  "nb_membres_total" integer DEFAULT 0,
  "nb_membres_femmes" integer DEFAULT 0,
  "nb_membres_certifies" integer DEFAULT 0,
  "parts_sociales_collectees_fcfa" numeric(16, 2) DEFAULT '0',
  "avances_octroyees_fcfa" numeric(16, 2) DEFAULT '0',
  "avances_remboursees_fcfa" numeric(16, 2) DEFAULT '0',
  "intrants_distribues_fcfa" numeric(16, 2) DEFAULT '0',
  "nb_lots_total" integer DEFAULT 0,
  "nb_lots_vendus" integer DEFAULT 0,
  "nb_lots_refoules" integer DEFAULT 0,
  "tonnage_refoule_kg" numeric(14, 2) DEFAULT '0',
  "nb_parcelles_gps" integer DEFAULT 0,
  "pct_conformite_eudr" numeric(6, 2) DEFAULT '0',
  "date_ouverture" date,
  "date_cloture" date,
  "duree_jours" integer DEFAULT 0,
  "archive_par" integer REFERENCES "users"("id"),
  "date_archivage" timestamp with time zone DEFAULT now(),
  "version_coopdigital" varchar(20),
  "checksum" varchar(64)
);
--> Statement-breakpoint
CREATE TABLE IF NOT EXISTS "archive_livraisons" (
  "id" serial PRIMARY KEY NOT NULL,
  "cooperative_id" integer NOT NULL REFERENCES "cooperatives"("id"),
  "campagne_id" integer NOT NULL REFERENCES "campagnes"("id"),
  "livraison_id" integer,
  "fournisseur_id" integer,
  "fournisseur_nom" text,
  "fournisseur_type" varchar(50),
  "poids_net_kg" numeric(10, 2),
  "prix_unitaire_fcfa" integer,
  "montant_brut_fcfa" integer,
  "avance_deduite_fcfa" integer,
  "montant_net_fcfa" integer,
  "date_livraison" date,
  "delegue_nom" text,
  "zone" text,
  "created_at" timestamp with time zone
);
--> Statement-breakpoint
CREATE TABLE IF NOT EXISTS "archive_membres_snapshot" (
  "id" serial PRIMARY KEY NOT NULL,
  "cooperative_id" integer NOT NULL REFERENCES "cooperatives"("id"),
  "campagne_id" integer NOT NULL REFERENCES "campagnes"("id"),
  "membre_id" integer,
  "nom" text,
  "prenoms" text,
  "village" text,
  "section" text,
  "delegue_nom" text,
  "tonnage_livre_kg" numeric(12, 2) DEFAULT '0',
  "montant_percu_fcfa" integer DEFAULT 0,
  "avances_recues_fcfa" integer DEFAULT 0,
  "score_campagne" numeric(6, 2),
  "niveau_campagne" varchar(20),
  "nb_livraisons" integer DEFAULT 0,
  "certifie" boolean DEFAULT false,
  "actif_cette_campagne" boolean DEFAULT false
);
