CREATE TABLE IF NOT EXISTS "bons_carburant" (
  "id"                 serial PRIMARY KEY NOT NULL,
  "cooperative_id"     integer NOT NULL REFERENCES "cooperatives"("id"),
  "numero"             varchar(50) NOT NULL,
  "vehicule_id"        integer NOT NULL REFERENCES "vehicules"("id"),
  "chauffeur_id"       integer REFERENCES "chauffeurs"("id"),
  "type_carburant"     varchar(20) NOT NULL DEFAULT 'gasoil',
  "quantite_autorisee" numeric(10,3) NOT NULL,
  "station_service"    varchar(255),
  "motif"              text,
  "date_emission"      date NOT NULL,
  "statut"             varchar(20) NOT NULL DEFAULT 'brouillon',
  "approuve_par"       integer REFERENCES "users"("id"),
  "date_approbation"   timestamp with time zone,
  "date_utilisation"   date,
  "quantite_livree"    numeric(10,3),
  "prix_litre_fcfa"    numeric(10,2),
  "montant_fcfa"       numeric(14,2),
  "observations"       text,
  "created_by"         integer REFERENCES "users"("id"),
  "created_at"         timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at"         timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE("cooperative_id","numero")
);
