import { vi } from "vitest";

const makeTable = (name: string) => ({ _: { name } });

export const db = { select: vi.fn(), insert: vi.fn(), update: vi.fn(), delete: vi.fn(), execute: vi.fn() };
export const membresTable = makeTable("membres");
export const avancesTable = makeTable("avances");
export const campagnesTable = makeTable("campagnes");
export const livraisonsTable = makeTable("livraisons");
export const lotLivraisonsTable = makeTable("lot_livraisons");
export const lotsTable = makeTable("lots");
export const exportateursTable = makeTable("exportateurs");
export const usersTable = makeTable("users");
export const paiementsTable = makeTable("paiements");
export const intrantsTable = makeTable("intrants");
export const distributionsIntrantsTable = makeTable("distributions_intrants");
export const remboursementsIntrantsTable = makeTable("remboursements_intrants");
export const categoriesIntrantsTable = makeTable("categories_intrants");
export const approvisionnmentsIntrantsTable = makeTable("approvisionnments_intrants");
export const stocksTable = makeTable("stocks");
export const mouvementsStockTable = makeTable("mouvements_stock");
export const entrepotsTable = makeTable("entrepots");
export const fournisseursTable = makeTable("fournisseurs");
export const cooperativesTable = makeTable("cooperatives");
export const sessionsUtilisateursTable = makeTable("sessions_utilisateurs");
export const devisesTable = makeTable("devises");
export const tauxChangeTable = makeTable("taux_change");
export const ecrituresComptablesTable = makeTable("ecritures_comptables");
export const ecrituresEnAttenteTable = makeTable("ecritures_en_attente");
export const exercicesTable = makeTable("exercices");
export const planComptableTable = makeTable("plan_comptable");
export const configComptableTable = makeTable("config_comptable");
export const licencesTable = makeTable("licences");
export const plansAbonnementTable = makeTable("plans_abonnement");
export const historiqueSmsTable = makeTable("historique_sms");
export const historiqueRendementsTable = makeTable("historique_rendements");
export const parcellesTable = makeTable("parcelles");
export const ventesExportateursTable = makeTable("ventes_exportateurs");
export const zonesRisqueEudrTable = makeTable("zones_risque_eudr");
export const bilansCampagneTable = makeTable("bilans_campagne");
export const IndicateurRse = makeTable("indicateurs_rse");
