import { Router, type IRouter } from "express";
import { authMiddleware } from "../middlewares/auth";
import { tenantGuard } from "../middlewares/tenantGuard";
import healthRouter from "./health";
import authRouter from "./auth";
import m15Router from "./m15";
import saasRouter from "./saas";
import membresRouter from "./membres";
import avancesRouter from "./avances";
import livraisonsRouter from "./livraisons";
import dashboardRouter from "./dashboard";
import lotsRouter from "./lots";
import stocksRouter from "./stocks";
import exportateursRouter from "./exportateurs";
import communicationRouter from "./communication";
import comptabiliteRouter from "./comptabilite";
import etatsFinanciersRouter from "./etatsFinanciers";
import rapportsRouter from "./rapports";
import usersRouter from "./users";
import salairesRouter from "./salaires";
import campagnesRouter from "./campagnes";
import partsSocialesRouter from "./partsSociales";
import refusRouter from "./refus";
import fournisseursRouter from "./fournisseurs";
import paiementsRouter from "./paiements";
import intrantsRouter from "./intrants";
import empruntsRouter from "./emprunts";
import devisesRouter from "./devises";
import budgetRouter from "./budget";
import subventionsRouter from "./subventions";
import gouvernanceRouter from "./gouvernance";
import prixRouter from "./prix";
import scoringRouter from "./scoring";
import anomaliesRouter from "./anomalies";
import auditRouter from "./audit";
import notificationsRouter from "./notifications";
import configRouter from "./config";
import storageRouter from "./storage";
import portailRouter from "./portail";
import transportRouter from "./transport";
import peseeRouter from "./pesee";
import equipementsRouter from "./equipements";
import previsionsRouter from "./previsions";
import terrainRouter from "./terrain";
import deleguesRouter from "./delegues";
import parcellesRouter from "./parcelles";
import donsRouter from "./dons";
import planningCollecteRouter from "./planning-collecte";
import formationsRouter from "./formations";
import formationsRseRouter from "./formations-rse";
import caisseRouter from "./caisse";
import banqueRouter from "./banque";
import fiscaliteRouter from "./fiscalite";
import reconciliationRouter from "./reconciliation";
import investissementsRouter from "./investissements";
import supportRouter from "./support";
import setupRouter from "./setup";
import searchRouter from "./search";
import missionsRouter from "./missions";
import financesRouter from "./finances";
import expeditionsRouter from "./expeditions";

const router: IRouter = Router();

// Routers publics / auth propre (avant le guard global)
router.use(healthRouter);
router.use(setupRouter);
router.use(authRouter);
router.use(portailRouter);
router.use(terrainRouter);
router.use(deleguesRouter);
router.use(m15Router);
router.use(saasRouter);

// Guard global : auth + vérification licence pour toutes les routes coopérative
router.use(authMiddleware);
router.use(tenantGuard);

router.use(membresRouter);
router.use(avancesRouter);
router.use(campagnesRouter);
router.use(partsSocialesRouter);
router.use(livraisonsRouter);
router.use(dashboardRouter);
router.use(lotsRouter);
router.use(stocksRouter);
router.use(exportateursRouter);
router.use(communicationRouter);
router.use(comptabiliteRouter);
router.use(etatsFinanciersRouter);
router.use(rapportsRouter);
router.use(usersRouter);
router.use(salairesRouter);
router.use(refusRouter);
router.use(fournisseursRouter);
router.use(paiementsRouter);
router.use(intrantsRouter);
router.use(empruntsRouter);
router.use(devisesRouter);
router.use(budgetRouter);
router.use(subventionsRouter);
router.use(gouvernanceRouter);
router.use(prixRouter);
router.use(scoringRouter);
router.use(anomaliesRouter);
router.use(auditRouter);
router.use(notificationsRouter);
router.use(configRouter);
router.use(storageRouter);
router.use(transportRouter);
router.use(peseeRouter);
router.use(equipementsRouter);
router.use(previsionsRouter);
router.use(parcellesRouter);
router.use(donsRouter);
router.use(planningCollecteRouter);
router.use(formationsRouter);
router.use(formationsRseRouter);
router.use(caisseRouter);
router.use(banqueRouter);
router.use(fiscaliteRouter);
router.use(reconciliationRouter);
router.use(investissementsRouter);
router.use(supportRouter);
router.use(searchRouter);
router.use(missionsRouter);
router.use(financesRouter);
router.use(expeditionsRouter);

export default router;
