import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import membresRouter from "./membres";
import avancesRouter from "./avances";
import livraisonsRouter from "./livraisons";
import dashboardRouter from "./dashboard";
import lotsRouter from "./lots";
import stocksRouter from "./stocks";
import exportateursRouter from "./exportateurs";
import communicationRouter from "./communication";
import comptabiliteRouter from "./comptabilite";
import etatsFinanciersRouter from "./etatsFinanciers";
import rapportsRouter from "./rapports";
import usersRouter from "./users";
import salairesRouter from "./salaires";
import campagnesRouter from "./campagnes";
import partsSocialesRouter from "./partsSociales";
import refusRouter from "./refus";
import fournisseursRouter from "./fournisseurs";
import paiementsRouter from "./paiements";
import intrantsRouter from "./intrants";
import empruntsRouter from "./emprunts";
import devisesRouter from "./devises";
import budgetRouter from "./budget";
import subventionsRouter from "./subventions";
import gouvernanceRouter from "./gouvernance";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(membresRouter);
router.use(avancesRouter);
router.use(campagnesRouter);
router.use(partsSocialesRouter);
router.use(livraisonsRouter);
router.use(dashboardRouter);
router.use(lotsRouter);
router.use(stocksRouter);
router.use(exportateursRouter);
router.use(communicationRouter);
router.use(comptabiliteRouter);
router.use(etatsFinanciersRouter);
router.use(rapportsRouter);
router.use(usersRouter);
router.use(salairesRouter);
router.use(refusRouter);
router.use(fournisseursRouter);
router.use(paiementsRouter);
router.use(intrantsRouter);
router.use(empruntsRouter);
router.use(devisesRouter);
router.use(budgetRouter);
router.use(subventionsRouter);
router.use(gouvernanceRouter);

export default router;
